export const GET_ALL_SERVICES_REQUEST = "GET_ALL_SERVICES_REQUEST";
export const GET_ALL_SERVICES_SUCCESS = "GET_ALL_SERVICES_SUCCESS";
export const GET_ALL_SERVICES_ERROR = "GET_ALL_SERVICES_ERROR";

export const ADD_A_NEW_SERVICE_REQUEST = "ADD_A_NEW_SERVICE_REQUEST";
export const ADD_A_NEW_SERVICE_SUCCESS = "ADD_A_NEW_SERVICE_SUCCESS";
export const ADD_A_NEW_SERVICE_ERROR = "ADD_A_NEW_SERVICE_ERROR";

export const EDIT_A_SERVICE_REQUEST = "EDIT_A_SERVICE_REQUEST";
export const EDIT_A_SERVICE_SUCCESS = "EDIT_A_SERVICE_SUCCESS";
export const EDIT_A_SERVICE_ERROR = "EDIT_A_SERVICE_ERROR";

export const DELETE_A_SERVICE_REQUEST = "DELETE_A_SERVICE_REQUEST";
export const DELETE_A_SERVICE_SUCCESS = "DELETE_A_SERVICE_SUCCESS";
export const DELETE_A_SERVICE_ERROR = "DELETE_A_SERVICE_ERROR";


export const ADD_A_NEW_SERVICE_IMAGE_REQUEST = "ADD_A_NEW_SERVICE_IMAGE_REQUEST";
export const ADD_A_NEW_SERVICE_IMAGE_SUCCESS = "ADD_A_NEW_SERVICE_IMAGE_SUCCESS";
export const ADD_A_NEW_SERVICE_IMAGE_ERROR = "ADD_A_NEW_SERVICE_IMAGE_ERROR";

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const LOGIN_EXPIRED = "LOGIN_EXPIRED"