export const GET_ALL_SERVICES_REQUEST = "GET_ALL_SERVICES_REQUEST";
export const GET_ALL_SERVICES_SUCCESS = "GET_ALL_SERVICES_SUCCESS";
export const GET_ALL_SERVICES_ERROR = "GET_ALL_SERVICES_ERROR";

export const ADD_A_NEW_SERVICE_REQUEST = "ADD_A_NEW_SERVICE_REQUEST";
export const ADD_A_NEW_SERVICE_SUCCESS = "ADD_A_NEW_SERVICE_SUCCESS";
export const ADD_A_NEW_SERVICE_ERROR = "ADD_A_NEW_SERVICE_ERROR";

export const UPATE_A_SERVICE_REQUEST = "UPATE_A_SERVICE_REQUEST";
export const UPATE_A_SERVICE_SUCCESS = "UPATE_A_SERVICE_SUCCESS";
export const UPATE_A_SERVICE_ERROR = "UPATE_A_SERVICE_ERROR";

export const DELETE_A_SERVICE_REQUEST = "DELETE_A_SERVICE_REQUEST";
export const DELETE_A_SERVICE_SUCCESS = "DELETE_A_SERVICE_SUCCESS";
export const DELETE_A_SERVICE_ERROR = "DELETE_A_SERVICE_ERROR";


export const ADD_A_NEW_SERVICE_IMAGE_REQUEST = "ADD_A_NEW_SERVICE_IMAGE_REQUEST";
export const ADD_A_NEW_SERVICE_IMAGE_SUCCESS = "ADD_A_NEW_SERVICE_IMAGE_SUCCESS";
export const ADD_A_NEW_SERVICE_IMAGE_ERROR = "ADD_A_NEW_SERVICE_IMAGE_ERROR";